// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmDXoOCokrcrSSNkfrQZTOTEXmKdyd12s',
    appId: '1:636440398232:web:8a192eb4cedb89e6f9c3ed',
    messagingSenderId: '636440398232',
    projectId: 'unique-voice-351815',
    authDomain: 'unique-voice-351815.firebaseapp.com',
    databaseURL: 'https://unique-voice-351815-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'unique-voice-351815.appspot.com',
    measurementId: 'G-9RHJXWYQ2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANPj9xbPC8WNNKonHbWExcn7QMZmmmpYI',
    appId: '1:636440398232:android:8ceb2c65b3996eadf9c3ed',
    messagingSenderId: '636440398232',
    projectId: 'unique-voice-351815',
    databaseURL: 'https://unique-voice-351815-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'unique-voice-351815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBptYNp4mRhnpc3zyeC0k6-fqt5R-v89NA',
    appId: '1:636440398232:ios:a123137c7b0472aef9c3ed',
    messagingSenderId: '636440398232',
    projectId: 'unique-voice-351815',
    databaseURL: 'https://unique-voice-351815-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'unique-voice-351815.appspot.com',
    iosClientId: '636440398232-493bu2ikb110spr7tpb8no6pgpp3elau.apps.googleusercontent.com',
    iosBundleId: 'app.romanime.romanimeGame',
  );
}
